name: "Documentation Deploy"

on: 
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.9
    
    - name: Install distutils
      run: |
        sudo apt-get update

    - name: Create the new documentation
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "python3 -m pip install .[docs]"
        docs-folder: "docs/"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        #deploy_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        publish_dir: ./docs/_build/html
        allow_empty_commit: true
